services:
  astro:
    build: .
    container_name: astro-app
    ports:
      - "80:3000"
      - "443:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
